import { lstat, mkdir, mkdtemp, readdir, rename, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, join, resolve } from 'node:path'

export async function generatePlugin({ id, directory, sdkVersion = '^1.0.0' }) {
  if (typeof id !== 'string' || !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(id)) throw new Error('Invalid plugin ID')
  if (typeof directory !== 'string' || !directory.trim()) throw new Error('Destination is required')
  const target = resolve(directory)
  try {
    const info = await lstat(target)
    if (!info.isDirectory() || info.isSymbolicLink() || (await readdir(target)).length) throw new Error('Destination is not empty')
  } catch (error) { if (error.code !== 'ENOENT') throw error }
  const parent = dirname(target)
  await mkdir(parent, { recursive: true })
  const staging = await mkdtemp(join(parent, `.${basename(target)}-`))
  const toolId = `tools/local/${id}/echo`
  const modelName = `tools_local_${id.replace(/[.-]/g, '_')}_echo`
  const skill = `---\nname: ${id}-hello\ndescription: Use the ${id} echo tool when the user wants a message echoed.\n---\n\nCall ${modelName} with a message. This instruction does not grant tool authorization.\n`
  const files = {
    'package.json': JSON.stringify({ name: id, version: '0.1.0', type: 'module', exports: { '.': './dist/extension.js', './catalog': './dist/catalog.js', './presentation': './dist/presentation.js' }, files: ['dist', 'plugin.json', 'skills'], scripts: { build: 'tsc -p tsconfig.json && esbuild src/extension.ts src/catalog.ts src/presentation.ts src/view.html --outdir=dist --loader:.md=text --loader:.html=copy --bundle --platform=node --format=esm', test: 'npm run build && node --test tests/lifecycle.test.mjs', prepack: 'npm run build' }, dependencies: { '@action-driver/plugin-sdk': sdkVersion }, devDependencies: { typescript: '5.9.3', esbuild: '0.28.2' } }, null, 2) + '\n',
    'plugin.json': JSON.stringify({ id, version: '0.1.0', sdk: '^1.0.0', entry: 'dist/extension.js', catalog: 'dist/catalog.js', platforms: ['darwin-arm64', 'darwin-x64', 'linux-arm64', 'linux-x64', 'win32-arm64', 'win32-x64'], activation: [`onTool:${toolId}`], contributions: [{ kind: 'tool', id: toolId, modelName }, { kind: 'skill', id: `${id}.hello` }, { kind: 'command', id: `${id}.echo-command` }, { kind: 'view', id: `${id}.dashboard` }, { kind: 'menu', id: `${id}.echo-menu` }], views: [{ id: `${id}.dashboard`, title: `${id} 面板`, container: 'sidebar', entry: 'dist/view.html' }], menus: [{ id: `${id}.echo-menu`, title: '回显消息', command: `${id}.echo-command`, location: 'plugins-menu' }], dependencies: [] }, null, 2) + '\n',
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', strict: true, declaration: true, outDir: 'dist', rootDir: 'src', lib: ['ES2022', 'DOM'], skipLibCheck: true }, include: ['src'] }, null, 2) + '\n',
    'src/catalog.ts': `import type { PluginCatalog, ToolDefinition } from '@action-driver/plugin-sdk'\nimport content from '../skills/hello/SKILL.md?raw'\nimport { presentations } from './presentation.js'\n\nexport const echoDefinition: ToolDefinition = {\n  id: '${toolId}', version: 1, modelName: '${modelName}', description: 'Echo a message',\n  presentation: presentations['${toolId}'],\n  inputSchema: { type: 'object', properties: { message: { type: 'string' } }, required: ['message'], additionalProperties: false },\n  risk: 'low', sideEffects: { filesystem: 'none', network: false }, timeoutMs: 1000\n}\n\nexport const catalog: PluginCatalog = {\n  tools: [echoDefinition],\n  skills: [{ id: '${id}.hello', name: '${id}-hello', description: 'Echo a message', content, resources: ['skills/hello/SKILL.md'] }]\n}\n`,
    'src/presentation.ts': `import type { ToolPresentation } from '@action-driver/plugin-sdk'\n\nexport const presentations: Record<string, ToolPresentation> = {\n  '${toolId}': {\n    input: [{ label: '消息', path: 'message', kind: 'text' }],\n    output: [{ label: '回显消息', path: 'result.message', kind: 'text' }]\n  }\n}\n`,
    'src/execution.ts': `import { PluginError, type ToolExecutor } from '@action-driver/plugin-sdk'\n\nexport function createEchoExecutor(): ToolExecutor {\n  return { async *execute(call, signal) {\n    if (signal?.aborted) throw new PluginError('CANCELLED', 'Echo cancelled')\n    yield { kind: 'result', output: { message: String(call.arguments.message ?? '') } }\n  } }\n}\n`,
    'src/extension.ts': `import type { PluginContext, StopReason } from '@action-driver/plugin-sdk'\nimport { catalog, echoDefinition } from './catalog.js'\nimport { createEchoExecutor } from './execution.js'\n\nexport function activate(context: PluginContext): void {\n  context.api.tools.register(echoDefinition, createEchoExecutor())\n  context.api.contributions.register({ kind: 'skill', id: catalog.skills[0]!.id })\n  // View content stays inside the host-owned container; messages arrive through the typed bridge.\n  context.api.views.register('${id}.dashboard', async input => ({ echoed: input }))\n  // A menu entry binds a declared command; the host re-checks conditions and grants on click.\n  context.api.commands.register('${id}.echo-command', async input => ({ command: '${id}.echo-command', input }))\n  context.api.menus.register('${id}.echo-menu')\n}\n\nexport function deactivate(_reason: StopReason): void {\n  // The host owns and disposes registrations and resources, even if this hook fails.\n}\n`,
    'src/view.html': `<!doctype html>\n<html lang="zh">\n  <head><meta charset="utf-8" /><title>${id} 面板</title></head>\n  <body>\n    <h1>${id}</h1>\n    <p>插件视图由宿主容器加载，不接触渲染进程 API。</p>\n    <button id="echo" type="button">回显消息</button>\n    <pre id="output"></pre>\n    <script>\n      document.getElementById('echo').addEventListener('click', async () => {\n        const result = await window.productPanel.postMessage('echo', { message: 'hello' })\n        document.getElementById('output').textContent = JSON.stringify(result)\n      })\n    </script>\n  </body>\n</html>\n`,
    'src/raw-assets.d.ts': "declare module '*?raw' { const content: string; export default content }\n",
    'skills/hello/SKILL.md': skill,
    'tests/lifecycle.test.mjs': `import { test } from 'node:test'\nimport assert from 'node:assert/strict'\nimport { createPluginContext } from '@action-driver/plugin-sdk'\nimport { activate, deactivate } from '../dist/extension.js'\nimport { catalog } from '../dist/catalog.js'\n\ntest('activation and host cleanup own every contribution', async () => {\n  const live = new Set()\n  const own = id => { live.add(id); return { dispose() { live.delete(id) } } }\n  const context = createPluginContext({ pluginId: '${id}', version: '0.1.0', hostEpoch: 'test' }, {\n    tools: { register(definition) { return own(definition.id) } },\n    registrations: { register(contribution) { return own(contribution.id) } },\n    transport: { async request() { throw new Error('No host transport configured in this test') } }\n  })\n  assert.equal(live.size, 0)\n  assert.equal(catalog.tools[0].inputSchema.type, 'object')\n  activate(context)\n  assert.equal(live.size, 5)\n  deactivate('disabled')\n  await context.subscriptions.dispose()\n  assert.equal(live.size, 0)\n})\n`,
    '.gitignore': 'node_modules/\ndist/\n*.tgz\n',
    'README.md': `# ${id}\n\nInstall dependencies with npm install, build with npm run build, and run npm test. Package with npm pack.\n\nSkill instructions, the pure catalog and execution entry ship in this one plugin package. Import ${id}/catalog to compose tool schemas and Skill instructions without activation. Import ${id}/presentation for pure semantic input/output fields. The Action-Driver host manages activation, authorization, cancellation and cleanup. SDK 1.x is required.\n\nOptional availability: add \`"when": "plugin.${id}.ready"\` to the tool contribution in plugin.json, then set the key from an async activate hook with \`await context.api.context.set('plugin.${id}.ready', true)\` before registering the tool. Remove it with \`context.api.context.remove\` when needed; the host also clears keys when this plugin instance stops. Conditions support boolean keys, equality with string/number literals, !, &&, || and parentheses. An unknown key makes the entire condition false, even under !. Conditions never grant tool authorization.\n\nViews and menus are declared in plugin.json and require host UI protocol 2: a host that only speaks protocol 1 rejects the plugin with INCOMPATIBLE instead of dropping the entries. Register them with context.api.views.register and context.api.menus.register; a menu entry only binds a declared command and the host re-checks its condition and grants on every click.\n\nPlugins run as trusted user code; process isolation is not an OS sandbox.\n`
  }
  try {
    for (const [path, content] of Object.entries(files)) {
      const destination = join(staging, path)
      await mkdir(dirname(destination), { recursive: true })
      await writeFile(destination, content, { flag: 'wx' })
    }
    await rename(staging, target)
  } catch (error) { await rm(staging, { recursive: true, force: true }); throw error }
}
