// Generated by scripts/sync-plugin-skills.mjs; edit skills/imagegen/ instead.
import type { SkillContribution } from '@action-driver/plugin-sdk'
import content from '../skills/imagegen/SKILL.md?raw'
export const skill: SkillContribution = { ...{
  "id": "imagegen",
  "name": "imagegen",
  "description": "Use when the user asks Action-Driver to generate raster images, illustrations, photos, mockups, or visual variants from text. Shape precise prompts and call the available tools_local_image_generation_generate tool. This Skill does not enable a model or grant tool access by itself.",
  "resources": [
    "skills/imagegen/LICENSE.txt",
    "skills/imagegen/SKILL.md",
    "skills/imagegen/agents/openai.yaml",
    "skills/imagegen/assets/imagegen-small.svg",
    "skills/imagegen/assets/imagegen.png",
    "skills/imagegen/references/cli.md",
    "skills/imagegen/references/codex-network.md",
    "skills/imagegen/references/codex-original-skill.md",
    "skills/imagegen/references/image-api.md",
    "skills/imagegen/references/prompting.md",
    "skills/imagegen/references/sample-prompts.md",
    "skills/imagegen/scripts/image_gen.py",
    "skills/imagegen/scripts/remove_chroma_key.py"
  ]
}, content }
