// Generated by scripts/sync-plugin-skills.mjs; edit skills/skill-creator/ instead.
import type { SkillContribution } from '@actiondriver/plugin-sdk'
import content from '../skills/skill-creator/SKILL.md?raw'
export const skill: SkillContribution = { ...{
  "id": "skill-creator",
  "name": "Skill Creator",
  "description": "Create or revise a reusable ActionDriver Skill when the user asks for one.",
  "resources": [
    "skills/skill-creator/SKILL.md",
    "skills/skill-creator/agents/openai.yaml",
    "skills/skill-creator/assets/skill-creator-small.svg",
    "skills/skill-creator/assets/skill-creator.png",
    "skills/skill-creator/license.txt",
    "skills/skill-creator/references/codex-skill-creator.md",
    "skills/skill-creator/references/openai_yaml.md",
    "skills/skill-creator/scripts/generate_openai_yaml.py",
    "skills/skill-creator/scripts/init_skill.py",
    "skills/skill-creator/scripts/quick_validate.py"
  ]
}, content }
