// Generated by scripts/sync-plugin-skills.mjs; edit skills/pdf/ instead.
import type { SkillContribution } from '@actiondriver/plugin-sdk'
import content from '../skills/pdf/SKILL.md?raw'
export const skill: SkillContribution = { ...{
  "id": "pdf",
  "name": "pdf",
  "description": "Read, create, inspect, render, and verify PDF files where visual layout matters, including fillable AcroForms. Use Poppler rendering plus Python tools such as reportlab, pdfplumber, and pypdf for generation and extraction.",
  "resources": [
    "skills/pdf/SKILL.md",
    "skills/pdf/agents/openai.yaml",
    "skills/pdf/assets/file-document.png",
    "skills/pdf/container_tools/mark_artifact_operation_started.mjs"
  ]
}, content }
