// Generated by scripts/sync-plugin-skills.mjs; edit skills/spreadsheets/ instead.
import type { SkillContribution } from '@action-driver/plugin-sdk'
import content from '../skills/spreadsheets/SKILL.md?raw'
export const skill: SkillContribution = { ...{
  "id": "spreadsheets",
  "name": "Spreadsheets",
  "description": "Use skill when user requests to create, modify, analyze, visualize, or work with spreadsheet files (`.xlsx`, `.xls`, `.csv`, `.tsv`) or Google Sheets with formulas, formatting, charts, tables, and recalculation. Do not use for live controlling Microsoft Excel app or a live Excel session.",
  "resources": [
    "skills/spreadsheets/SKILL.md",
    "skills/spreadsheets/agents/openai.yaml",
    "skills/spreadsheets/artifact_tool_docs/API_QUICK_START.md",
    "skills/spreadsheets/artifact_tool_docs/DATA_TABLES.md",
    "skills/spreadsheets/artifact_tool_docs/SPARKLINES.md",
    "skills/spreadsheets/assets/file-spreadsheet.png",
    "skills/spreadsheets/container_tools/mark_artifact_operation_started.mjs",
    "skills/spreadsheets/domain_guidance/financial_models.md",
    "skills/spreadsheets/domain_guidance/healthcare.md",
    "skills/spreadsheets/domain_guidance/marketing_advertising.md",
    "skills/spreadsheets/domain_guidance/scientific_research.md",
    "skills/spreadsheets/features/charts.md",
    "skills/spreadsheets/references/image-references.md",
    "skills/spreadsheets/references/read_only_qna.md",
    "skills/spreadsheets/references/template-elicitation.md",
    "skills/spreadsheets/routing/google_sheets.md",
    "skills/spreadsheets/style_guidelines.md",
    "skills/spreadsheets/workflows/create_workflows.md",
    "skills/spreadsheets/workflows/edit_workflows.md"
  ]
}, content }
