// Candidate macOS Sky exports. Native host acceptance remains a separate gate.
export { fromFilePath, toBase64, toDataUrl } from './core/bytes.js'
export { MacComputerUseClient } from './mac/client.js'
export type { ClientOptions, RequestOptions } from './mac/client.js'
export { NativePipeTransport } from './mac/native-pipe.js'
export type { NativePipe, NativeRequest, RequestTransport } from './mac/native-pipe.js'
export { createNativeTransport } from './mac/native-connection.js'
export type { NativeHost } from './mac/native-connection.js'
export { encodeMessageFrame, decodeMessageFrames } from './mac/rpc-codec.js'
export { ComputerUseError, ComputerUseTransportError, ServerErrorCode } from './mac/errors.js'
export type { DiscoveredApp, AppPolicyResult, WindowAppState, AudioResult } from './mac/types.js'
export { createMacComputer } from './mac/computer.js'
export { createComputerUsePolicy } from './mac/policy.js'
export type { PolicyHost, TelemetrySink, ComputerUsePolicy } from './mac/policy.js'
export { createComputerUseTelemetry } from './mac/telemetry.js'
export type { TelemetryHost, TelemetrySdk } from './mac/telemetry.js'
export { windowResult } from './mac/window-result.js'
export { createSkyProxy } from './sky-proxy.js'
export { sky } from './sky.js'
export { runCommand } from './core/command.js'
export type { CommandOptions, CommandResult } from './core/command.js'
export { resolvePackageBin } from './core/package-bin.js'
export type { Direction, MouseButton, Point, SkyClient, Options, Window } from './types/index.js'
export { env, unimplemented } from './core/env.js'
export type { EnvArgs } from './core/env.js'
